### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by neodon** [TimDaub/better-sqlite3-session-store#7]
Hello.  Thank you for creating this project.  I use better-sqlite3 in my projects and so this was perfect for adding a session store.

I use TypeScript for my projects and so I ended up making a copy of this package and converting it to TypeScript.

I was wondering if you'd be interested in some pull requests to add:

- TypeScript support with a build step to transpile the TypeScript away and bundle the types into the output
- Linting with ESLint & formatting with Prettier (I can recommend settings but it's whatever you want)

**Comment by TimDaub** [comment]
sure, I'm open to it. Please send a PR and we can discuss. thx

**Comment by neodon** [comment]
I've made a bit of progress in my fork.  Before I continue I wanted to ask you if you'd be willing to accept a breaking change, possibly as a pre-release and/or a 1.0.0 version to avoid breaking existing installations.

The challenge I ran into was the usage of `const SqliteStore = require('better-sqlite3-session-store')(session)`.  This syntax is concise for CommonJS, but causes issues when trying to get types exported.  I did try to preserve the existing behavior with no luck.

The new usage would be:
- es5: `const SqliteStore = require('better-sqlite3-session-store').default`
- es6/TypeScript: `import SqliteStore from 'better-sqlite3-session-store'`

This change would also prevent a user from passing in their own session.Store base class, but I was wondering if that was ever a goal.

**Comment by TimDaub** [comment]
If we want to use ESM in our codebase, we must add an extra build step to ship valid cjs. 

It's possible to ship dual packages that work with esm and cjs.

Guide: https://2ality.com/2019/10/hybrid-npm-packages.html

**Comment by neodon** [comment]
Yes, I am familiar with the concept and have a setup in another project to ship both ESM and CJS.  I'd like to tackle that at a later time though since other ESM modules can still import CJS modules.

I only showed the import example because it's how TypeScript would consume the package with a default export, even though it's also considered ESM syntax.

I'm interested in getting rid of the exported factory function that takes a class argument and dynamically extends from it.  This would simplify things around modernizing the package for both TypeScript and (in the future) ESM.

**Comment by neodon** [comment]
I think I might be overengineering this.  Let me take a step back now that I'm more familiar with how the code works and its dependencies.  I'll follow up this weekend with hopefully a smaller step forward that won't break anything.

**Comment by TimDaub** [comment]
hey since we added types in #8, @neodon I'm closing this issue. Feel free to reopen in case more is work necessary.
